# Replication and robustness checks for AJR (2001), using ivdoctr's base sample.
# 2SLS is estimated with AER::ivreg, which reports conventional IV standard errors.

set.seed(20260717) # No stochastic steps are used; set for project convention.

suppressPackageStartupMessages({
  library(ivdoctr)
  library(AER)
})

data(colonial, package = "ivdoctr")
colonial <- as.data.frame(colonial) # The packaged object may be a data.table.

# Each specification uses complete cases on its outcome, endogenous regressor,
# excluded instrument, and included controls.
specifications <- list(
  "Headline: no controls" = list(
    keep = rep(TRUE, nrow(colonial)), controls = character(0)
  ),
  "Add latitude" = list(
    keep = rep(TRUE, nrow(colonial)), controls = "lat_abst"
  ),
  "Add continent controls" = list(
    keep = rep(TRUE, nrow(colonial)), controls = c("africa", "asia")
  ),
  "Drop neo-Europes" = list(
    keep = !(colonial$shortnam %in% c("AUS", "CAN", "NZL", "USA")),
    controls = character(0)
  ),
  "Africa only" = list(
    keep = colonial$africa == 1, controls = character(0)
  )
)

fit_specification <- function(specification) {
  controls <- specification$controls
  vars_needed <- c("logpgp95", "avexpr", "logem4", controls)
  dat <- colonial[specification$keep, vars_needed, drop = FALSE]
  dat <- dat[complete.cases(dat), , drop = FALSE]

  outcome_rhs <- paste(c("avexpr", controls), collapse = " + ")
  first_stage_rhs <- paste(c("logem4", controls), collapse = " + ")
  instrument_rhs <- paste(c("logem4", controls), collapse = " + ")

  ols <- lm(as.formula(paste("logpgp95 ~", outcome_rhs)), data = dat)
  # Included exogenous controls appear after |, instrumenting themselves.
  iv <- AER::ivreg(
    Formula::as.Formula(paste("logpgp95 ~", outcome_rhs, "|", instrument_rhs)),
    data = dat
  )
  first_stage <- lm(as.formula(paste("avexpr ~", first_stage_rhs)), data = dat)
  restricted_rhs <- if (length(controls)) paste(controls, collapse = " + ") else "1"
  first_stage_restricted <- lm(
    as.formula(paste("avexpr ~", restricted_rhs)), data = dat
  )

  # This nested-model F is the partial first-stage F for the excluded logem4.
  excluded_f <- anova(first_stage_restricted, first_stage)$F[2]
  ols_summary <- summary(ols)$coefficients
  iv_summary <- summary(iv)$coefficients

  data.frame(
    n = nrow(dat),
    ols = unname(coef(ols)["avexpr"]),
    ols_se = unname(ols_summary["avexpr", "Std. Error"]),
    iv_2sls = unname(coef(iv)["avexpr"]),
    iv_2sls_se = unname(iv_summary["avexpr", "Std. Error"]),
    first_stage_coefficient = unname(coef(first_stage)["logem4"]),
    first_stage_f = excluded_f,
    weak_identification = excluded_f < 10,
    row.names = NULL
  )
}

results <- do.call(rbind, lapply(specifications, fit_specification))
results <- cbind(specification = names(specifications), results)

# Guard against a hand-written reporting table drifting from the analysis.
expected_n <- c(64L, 64L, 64L, 60L, 27L)
expected_ols <- c(0.522, 0.468, 0.434, 0.487, 0.302)
expected_iv <- c(0.944, 0.996, 0.839, 1.281, 2.400)
stopifnot(
  identical(results$n, expected_n),
  isTRUE(all.equal(round(results$ols, 3), expected_ols)),
  isTRUE(all.equal(round(results$iv_2sls, 3), expected_iv))
)

format_estimate <- function(estimate, se) {
  sprintf("%.3f (SE %.3f)", estimate, se)
}

ols_display <- mapply(format_estimate, results$ols, results$ols_se)
iv_display <- ifelse(
  results$weak_identification,
  sprintf("%.3f (not reported: weak IV)", results$iv_2sls),
  mapply(format_estimate, results$iv_2sls, results$iv_2sls_se)
)
flag_display <- ifelse(
  results$weak_identification, "**Weak; conventional IV inference unreliable**",
  ifelse(results$specification == "Add continent controls", "Not weak (borderline)", "Not weak")
)

table_rows <- vapply(seq_len(nrow(results)), function(i) {
  paste0(
    "| ", results$specification[i], " | ", results$n[i], " | ", ols_display[i],
    " | ", iv_display[i], " | ", sprintf("%.3f", results$first_stage_coefficient[i]),
    " | ", sprintf("%.3f", results$first_stage_f[i]), " | ", flag_display[i], " |"
  )
}, character(1))

table_text <- c(
  "# AJR base-sample robustness checks",
  "",
  "Generated by `script.R`. All models use `ivdoctr::colonial` and `AER::ivreg` for 2SLS. The first-stage F is the partial nested-model F test for the excluded instrument, `logem4`, conditional on the controls shown. ‘Weak’ uses the stated rule of thumb, F < 10. Coefficients are in log-income units per one-unit change in expropriation protection; parentheses give conventional standard errors.",
  "",
  "| Specification | N | OLS: `avexpr` | 2SLS: `avexpr` | First-stage `logem4` coefficient | First-stage F | Identification flag |",
  "|---|---:|---:|---:|---:|---:|---|",
  table_rows,
  "",
  "For the two weak specifications, the table retains the 2SLS point estimate for transparency but omits its conventional standard error: weak identification makes conventional 2SLS inference unreliable. No weak-IV-robust confidence sets are reported here. In the Africa-only model, the collapsed first stage (F = 0.298), rather than a conventional 2SLS standard error, is the decisive limitation."
)
writeLines(table_text, "robustness-table.md")

print(results, row.names = FALSE)
cat("\nWrote robustness-table.md. Weak identification is flagged where the partial first-stage F is below 10.\n")
